# ===================
# WIKILINK SUPPORT
# ===================
# This feature is experimental and not guaranteed to be fully stable.
# It works well for small/medium personal sites such as digital gardens or knowledge bases.
# However, it is NOT recommended for large-scale documentation sites.
# Notes:
# - Does NOT support image syntax like ![[image.jpg]]
#   Please use standard Markdown: ![alt text](image.jpg)
# - Enabled by setting params.wikilink = true

wikilink: true
