author    : Putra Jaya
emoji     : 📚
logo      : assets/images/logo.png

# PAGE SETTING
defaultEditPage : true
defaultMath     : false
defaultGiscus   : true

# GIT INFO
ghrepo          : masputrawae/silver-fishstick
branch          : main

# WIDGET TAXONOMY
displayTaxonomies:
  - tags
  - categories

# GISCUS
giscusConfig:
  dataRepo              : "masputrawae/masputrawae.github.io"
  dataRepoId            : "R_kgDOPAdouw"
  dataCategory          : "General"
  dataCategoryId        : "DIC_kwDOPAdou84CtQ2d"
  dataMapping           : "title"
  dataStrict            : 0
  dataReactionsEnabled  : 1
  dataEmitMetadata      : 1
  dataInputPosition     : "top"

# FAVICONS
favicons:
  - rel   : icon
    type  : image/x-icon
    href  : assets/favicons/favicon.ico

  - rel   : apple-touch-icon
    type  : image/png
    size  : 180x180
    href  : assets/favicons/apple-touch-icon.png

  - rel   : icon
    type  : image/png
    size  : 32x32
    href  : assets/favicons/favicon-32x32.png

  - rel   : icon
    type  : image/png
    size  : 16x16
    href  : assets/favicons/favicon-16x16.png

  - rel   : icon
    type  : image/png
    size  : 192x192
    href  : assets/favicons/android-chrome-192x192.png

  - rel   : icon
    type  : image/png
    size  : 512x512
    href  : assets/favicons/android-chrome-512x512.png

# SOCIAL LINK
social:
  - name  : Instagram
    url   : https://www.instagram.com/masputrawae/
    icon  : instagram

  - name  : Twitter X
    url   : https://x.com/Masputrawae
    icon  : twitter-x

  - name  : Facebook
    url   : https://facebook.com/Masputrawae
    icon  : facebook

  - name  : Discord
    url   : https://discord.gg/nM4EP8DJFZ
    icon  : discord

  - name  : GitHub
    url   : https://github.com/masputrawae/
    icon  : github

# Theme Credit (optional)
# themeCredit: Theme by Putra Jaya